// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// costMatrix
arma::mat costMatrix(arma::mat& y, arma::mat& X, double Lmin);
RcppExport SEXP _MPWR_costMatrix(SEXP ySEXP, SEXP XSEXP, SEXP LminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type Lmin(LminSEXP);
    rcpp_result_gen = Rcpp::wrap(costMatrix(y, X, Lmin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MPWR_costMatrix", (DL_FUNC) &_MPWR_costMatrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MPWR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
